/* eslint-disable */
const formHeaders = ({gun, start, end, il}) => {
  return {
    'draw': 1,
    'columns[0][data]': 'IlAdi',
    'columns[0][name]': '',
    'columns[0][searchable]': true,
    'columns[0][orderable]': true,
    'columns[0][search][value]': '',
    'columns[0][search][regex]': false,
    'columns[1][data]': 'IlceAdi',
    'columns[1][name]': '',
    'columns[1][searchable]': true,
    'columns[1][orderable]': true,
    'columns[1][search][value]': '',
    'columns[1][search][regex]': false,
    'columns[2][data]': 'DegreeSicilNo',
    'columns[2][name]': '',
    'columns[2][searchable]': true,
    'columns[2][orderable]': true,
    'columns[2][search][value]': '',
    'columns[2][search][regex]': false,
    'columns[3][data]': 'AdSoyad',
    'columns[3][name]': '',
    'columns[3][searchable]': true,
    'columns[3][orderable]': true,
    'columns[3][search][value]': '',
    'columns[3][search][regex]': false,
    'columns[4][data]': 'Unvan',
    'columns[4][name]': '',
    'columns[4][searchable]': true,
    'columns[4][orderable]': true,
    'columns[4][search][value]': '',
    'columns[4][search][regex]': false,
    'columns[5][data]': 'SaticiSinifiAdi',
    'columns[5][name]': '',
    'columns[5][searchable]': true,
    'columns[5][orderable]': true,
    'columns[5][search][value]': '',
    'columns[5][search][regex]': false,
    'columns[6][data]': 'IkametAdres',
    'columns[6][name]': '',
    'columns[6][searchable]': true,
    'columns[6][orderable]': true,
    'columns[6][search][value]': '',
    'columns[6][search][regex]': false,
    'columns[7][name]': '',
    'columns[7][searchable]': true,
    'columns[7][orderable]': true,
    'columns[7][search][value]': '',
    'columns[7][search][regex]': false,
    'order[0][column]': 0,
    'order[0][dir]': 'asc',
    'start': 0,
    'length': 1000,
    'search[value]': '',
    'search[regex]': false,
    'VBasvuruKamuyaAcikAramaAra.IlRefId': il || '',
    'VBasvuruKamuyaAcikAramaAra.DegreeSicilNo': 'PT',
    'VBasvuruKamuyaAcikAramaAra.TCKimlikNo': '',
    'VBasvuruKamuyaAcikAramaAra.Unvan': '',
    'VBasvuruKamuyaAcikAramaAra.VergiNo': '',
    'VBasvuruKamuyaAcikAramaAra.Ad': '',
    'VBasvuruKamuyaAcikAramaAra.Soyad': '',
    // 'VBasvuruKamuyaAcikAramaAra.TarihAraligiId': gun,
    'VBasvuruKamuyaAcikAramaAra.FiiliDurumRefId': 116,
    'VBasvuruKamuyaAcikAramaAra.MulkuAmirOnayTarihiIlk': start || gun,
    'VBasvuruKamuyaAcikAramaAra.MulkuAmirOnayTarihiSon': end || gun
  }
};

export {formHeaders};